### ISSUE TITLE
How should I cache the routes?

### ISSUE THREAD

**Issue by inod** [mrjgreen/phroute#21]
Hello, You mention caching the `$router->getData()` in your example, but you're using closures so it looks like `serialize($router->getData())` is not an option.

I'm using closures too, how do you suggest I cache the $router->getData()?

**Comment by mrjgreen** [comment]
Instead of using closures, I would recommend using a class with a method like this:

~~~PHP
$routeCollector->get('/', array('HomeRoutes', 'index');
$routeCollector->get('/login', array('HomeRoutes', 'login');
$routeCollector->post('/login', array('HomeRoutes', 'postLogin');

// or using the "restful" controller helper to achieve the same result:

$routeCollector->controller('/', 'HomeController');
~~~

Where HomeController could look like:

~~~PHP
class HomeController
{
    public function getIndex()
    {
    }

    public function getLogin()
    {
    }

    public function postLogin()
    {
    }
}
~~~

Hope that helps! Let me know if theres anything else :)

**Comment by inod** [comment]
I got it, thanks.

My initial thinking was to try some simple conditional checking inside it like some other routers permit and even encourage.
But I believe it's better to leave routers to routing and do logic elsewhere, however simple it might be.

Is this the right mindset?

**Comment by mrjgreen** [comment]
Yes I'd agree with you there.
